import openai

openai.api_key = "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"

# list to store the prompts given by user and the answers generated by ChatGpt for the prompts
# this makes the chatbot remember the history
messages = []

# makes the chatbot behave like the role we intend it to play
system_msg = input("What type of chatbot would you like to create?\n")
messages.append({"role": "system", "content": system_msg})

print("Your new assistant is ready!")
while input != "quit()":
    message = input()
    messages.append({"role": "user", "content": message})

    # chatbot's response
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=messages)

    # filter the response to get the required reply
    reply = response["choices"][0]["message"]["content"]

    messages.append({"role": "assistant", "content": reply})

    # print the reply
    print("\n" + reply + "\n")
